alias cl='clear'
alias wf='cd /usr/local/git_tree/main/apps/oozie/workflows/'
alias gpr='git pull --rebase'
alias mylog='git log --author=Federico Cavaletto'
alias gs='git status'
alias cn='motd | grep cluster | grep -o "[a-z]*_[a-z]*4"'
